"""add application_profile table

Revision ID: 40671a1b36d3
Revises: f95dca27f569
Create Date: 2026-04-09 13:28:11.726460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40671a1b36d3'
down_revision: Union[str, Sequence[str], None] = 'f95dca27f569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('cover_letter_template', sa.Text(), nullable=True),
    sa.Column('name_pronunciation', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.String(length=255), nullable=True),
    sa.Column('timeline_notes', sa.Text(), nullable=True),
    sa.Column('requires_visa_sponsorship', sa.Boolean(), nullable=True),
    sa.Column('requires_future_visa_sponsorship', sa.Boolean(), nullable=True),
    sa.Column('willing_to_relocate', sa.Boolean(), nullable=True),
    sa.Column('office_availability', sa.String(length=100), nullable=True),
    sa.Column('eeoc_gender', sa.String(length=100), nullable=True),
    sa.Column('eeoc_race', sa.String(length=100), nullable=True),
    sa.Column('eeoc_veteran_status', sa.String(length=100), nullable=True),
    sa.Column('eeoc_disability_status', sa.String(length=100), nullable=True),
    sa.Column('custom_answers', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_profiles')
    # ### end Alembic commands ###
