"""add country and eeoc_ethnicity to application_profile

Revision ID: c1b54e9173c2
Revises: 84b652127e81
Create Date: 2026-04-09 14:00:09.742024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1b54e9173c2'
down_revision: Union[str, Sequence[str], None] = '84b652127e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_profiles', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('application_profiles', sa.Column('eeoc_ethnicity', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_profiles', 'eeoc_ethnicity')
    op.drop_column('application_profiles', 'country')
    # ### end Alembic commands ###
