"""add autofill profile fields

Revision ID: f95dca27f569
Revises: b07e9949c450
Create Date: 2026-04-09 11:22:10.217461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f95dca27f569'
down_revision: Union[str, Sequence[str], None] = 'b07e9949c450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('user_profiles', sa.Column('linkedin_url', sa.String(length=500), nullable=True))
    op.add_column('user_profiles', sa.Column('website_url', sa.String(length=500), nullable=True))
    op.add_column('user_profiles', sa.Column('work_authorization', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'work_authorization')
    op.drop_column('user_profiles', 'website_url')
    op.drop_column('user_profiles', 'linkedin_url')
    op.drop_column('user_profiles', 'phone')
    # ### end Alembic commands ###
